---

language: python
addons:
  chrome: stable
  firefox: latest
python:
  - '3.6'
services: docker

# Only execute travis in master or PR to master
branches:
  only:
  - master

stages:
  - name: "[backend] unit tests"
  - name: "[backend] update-dependencies"
    if: branch = master AND type != pull_request
  - name: "[frontend] unit test"
  - name: "end to end tests"
  - name: dockerhub-build
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: "[backend] unit tests"
      before_install:
        - cd api
      install:
        - pip install -r requirements_test.txt
      script:
        - make test
    - stage: "[backend] update-dependencies"
      before_install:
        - cd api
      install:
        - pip install -r requirements_test.txt
        - bash scripts/update_dependencies.sh
      script:
        - bash scripts/update_dependencies.sh
      after_success:
        - git config user.name "tracis-ci"
        - git config user.email "travis-ci@travis-ci.org"
        - git add requirements.txt
        - git commit -m 'Update requirements.txt'
        - git push "https://$GITHUB_TOKEN@github.com/$TRAVIS_REPO_SLUG" HEAD:$TRAVIS_BRANCH
      env:
        - secure: __GITHUB_TOKEN__
    - stage: "[frontend] unit test"
      before_install:
        - cd front
      install:
        - npm install
      script:
        - npm run lint
        - npm run test:unit
    - stage: "end to end tests"
      install:
        - skip
      before_script:
        - "export DISPLAY=:99.0"
        - "sh -e /etc/init.d/xvfb start"
        - sleep 3
      script:
        - make test
    - stage: dockerhub-build
      install: skip
      script:
        - "curl -H 'Content-Type: application/json' --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/pando85/quotes-simple-web/trigger/$DOCKERHUB_TOKEN/"
      env:
        - secure: __DOCKERHUB_TOKEN__
