---
sudo: true

dist: xenial
language: python
python:
  - '3.7'

cache: pip
before_cache:
  - rm -f $HOME/.cache/pip/log/debug.log

# Only execute travis in master or PR to master
branches:
  only:
  - master

stages:
  - name: "unit tests"
  - name: "update-dependencies"
    if: branch = master AND type != pull_request
  - name: dockerhub-build
    if: branch = master AND type != pull_request

jobs:
  include:
    - stage: "unit tests"
      install:
        - make requirements_test
      script:
        - make test
    - stage: "update-dependencies"
      install:
        - make requirements_test
      script:
        - bash .ci/update_dependencies.sh
      env:
        - secure: "m13MeeS/hlBE/k2u1U/mCebacyqwgV42pbAw1Zb336N9s7W4/kZwF6/V3ZtnFcmSqyUV9rrhnBtE2VYJj1gd6kXlM7DAtPBLWkH5elmwWkTA9dxCD+Uv+S4A9KMpsM78pZM9rtOZwWWPupzzJ9pjNa8XoCbYCOd+F7C2J6wddbYN1knObPd+W4WRw/hCOBklh6eWTuNoeh5wrKH00peD3kceWhb0niIpeB5k7MTfnZkeOVX0scmPrVuQeUHQCKV3vx62RpKTdi+hF+AAxTSD9MUDl2GNlYh+CpxAQsNpzkVoZki22vXLcpkiciTSuOND2zE2d7SVyz+PMw1MzVF6F/KMipnpaQWBLTa5tTU2ohX2MxP+Ut7fXxBh/CwuecuDxTaQ+HKxbqGRWgpETsX3RJXLzkW38lr4qxb8VITzl9DVDL9IJnvr3QPv5KRHv3IKEZjocjYEwXuDv+03b4poGyWY1/cQLq94RKM8BdArejJGqIFxcJxAL1HG1kzK5bwsgTQsGRo5tSFJ8NEIARrPQ9SMxFMoJh+HCIaQb9y1A/w2eLYtZT5YbHhgD1zs8lzopxJnDy/wcXGqogaxKXARmneUOfd+uc75rM0cGciHyovM7xbPpKwjX+ba2YDa8R8iZV8vhepObxdpRnpogoPqP3x9WXVwKe6m6sPepFuNCLw="
    - stage: dockerhub-build
      install: skip
      script:
        - "curl -H 'Content-Type: application/json' --data '{\"build\": true}' -X POST https://registry.hub.docker.com/u/pando85/auth/trigger/$DOCKERHUB_TOKEN/"
      env:
        - secure: "L66xRr5d7XbfGHrE6r05MDwioSX+KGNSP7JE39n9TE5A7nTCBc1w9Aou29925QC5d9sO3N3PKxzdZ5r9LnPaPFsj5O/7ldNEu+urYQ1pSJcx80fGw5ed8er7qypqiCtXV9gnxqwFWfkp4PAhe3LW2n4XDJRnUjJuERyQJ8/oturJFOmGZadryWORKrncmz7sb/oheYdYjPuLDrpVTc11jsFyH9c9KlpaXinK6Tvgd5Ln8A5q41kCfAD+i8MBm930+osfUD+BqU6RrtMaS1kC5cMeKHyINnX40oqKPnrCxbcVwXMTMxf9WJml5tNLP0iS6ebLYQNgIcZxQqP6QWVasvQiSVZRtvRLcb3OkEhIdKyeP35AQZnXU2f6XgZ5qjuYJqW2eY7LIAtvCUEtUydHVLxsCL8GZOjtulcV2MsOzcGJgde9O4VIOV48cPutOqr0NQPqD4WwUBYB21fKITuIxnIrfgeh8M7yq+aJ5lQZvtVxCK3kSqJ068mEeNnmXoyVagOYciOE2MPPPTY4s/F+VIS0cL88Vr/DnTw7/c/0AW587ldlFbCnbFWk2WGcncE5gMqbONIM4YmAbLUmFRk7qc/crP4YKu5cwkXKxjvKAbFwB805OV0R36bGpIwLxhNx3xvvRFXO1aajuAd1Eo80JQFSR0T8k4jTOXf6q8E1OIo="
